### ISSUE TITLE
Allow reference local values inside string evaluations

### ISSUE THREAD

**Issue by iarkhanhelsky** [vizor-games/jac#2]
Allow to reference values on same level of nested objects - e.g.

```yaml
default:
  project: 
     network: fb
     server_name: "#{c.project['network']}-srv"
```

can be replaced with

```yaml
default:
  project: 
     network: fb
     server_name: "#{self['network']}-srv"
```
